## Assignment 3

**TU Delft and WUR**<br>
**Q1 2024**<br>
**Instructor:** Theodoros Chatzivasileiadis <br>
**Instructor:** Hans Hoogenboom <br>
**TA:** Ka Yi Chua <br>
**[Metropolitan Data 1](https://jhoogenboom.github.io/spatial-data-science/_index.html)** <br>

__This homework assignment document will guide you through five tasks in cleaning your data.__

1. Reading and Summarizing the Data.
2. Subsetting the Data.
3. Manage Missing Data.
4. Shape the Data.
5. Saving the Results. 

# NB: From now on you should submit 1) your notebook with the answers, remember that comments are good practice, 2) a working Git page with your assignment

## Exercise 1: Loading the data:

- Load the `goodreads.csv` file into Python
- Explore it by looking at first and last 5 rows
- Change the column names to `["rating", 'review_count', 'isbn', 'booktype','author_url', 'year', 'genre_urls', 'dir','rating_count', 'name']`

In [74]:
# your code here
# use many cells if you like to structure your code well
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

#Read the data into a dataframe
df = pd.read_csv("C:\\Users\\MSI\\Documents\\Data_one\\goodreads.csv", encoding='utf-8')

#Display the first five rows of the dataframe
df.head()

,rating,review_count,isbn,booktype,year,genre_urls,dir,rating_count,name,author
0,4.40,136455.0,0439023483,good_reads:book,2008.0,/genres/young-adult|/genres/science-fiction|/g...,dir01/2767052-the-hunger-games.html,2958974.0,"The Hunger Games (The Hunger Games, #1)",Suzanne_Collins
1,4.41,16648.0,0439358078,good_reads:book,2003.0,/genres/fantasy|/genres/young-adult|/genres/fi...,dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...,1284478.0,Harry Potter and the Order of the Phoenix (Har...,J_K_Rowling
2,3.56,85746.0,0316015849,good_reads:book,2005.0,/genres/young-adult|/genres/fantasy|/genres/ro...,dir01/41865.Twilight.html,2579564.0,"Twilight (Twilight, #1)",Stephenie_Meyer
3,4.23,47906.0,0061120081,good_reads:book,1960.0,/genres/classics|/genres/fiction|/genres/histo...,dir01/2657.To_Kill_a_Mockingbird.html,2078123.0,To Kill a Mockingbird,Harper_Lee
4,4.23,34772.0,0679783261,good_reads:book,1813.0,/genres/classics|/genres/fiction|/genres/roman...,dir01/1885.Pride_and_Prejudice.html,1388992.0,Pride and Prejudice,Jane_Austen

In [75]:
#Display the last five rows of the dataframe
df.tail()

,rating,review_count,isbn,booktype,year,genre_urls,dir,rating_count,name,author
5988,4.17,2226.0,0767913736,good_reads:book,2005.0,/genres/history|/genres/non-fiction|/genres/bi...,dir60/78508.The_River_of_Doubt.html,16618.0,The River of Doubt,Candice_Millard
5989,3.99,775.0,1416909427,good_reads:book,2006.0,/genres/young-adult|/genres/realistic-fiction|...,dir60/259068.Shug.html,6179.0,Shug,Jenny_Han
5990,3.78,540.0,1620612321,good_reads:book,2012.0,/genres/contemporary|/genres/romance|/genres/y...,dir60/13503247-flawed.html,2971.0,Flawed,Kate_Avelynn
5991,3.91,281.0,NaN,good_reads:book,2006.0,/genres/religion|/genres/islam|/genres/religio...,dir60/2750008.html,3083.0,Ø£Ø³Ø¹Ø¯ Ø§Ù Ø±Ø£Ø© ÙÙ Ø§ÙØ¹Ø§ÙÙ,A_id_al_Qarni
5992,4.35,61.0,0786929081,good_reads:book,2001.0,/genres/fiction|/genres/fantasy|/genres/magic|...,dir60/66677.Legacy_of_the_Drow_Collector_s_Edi...,3982.0,Legacy of the Drow Collector's Edition (Legacy...,R_A_Salvatore

In [76]:
# reading the csv file, excluding the headers
df=pd.read_csv("C:\\Users\\MSI\\Documents\\Data_one\\goodreads.csv", header=None,
               names=["rating", 'review_count', 'isbn', 'booktype','author_url', 'year', 'genre_urls', 'dir','rating_count', 'name'],
)

# checking the dataframe
print( df.head())

   rating  review_count        isbn         booktype author_url  \
0  rating  review_count        isbn         booktype       year
1     4.4      136455.0  0439023483  good_reads:book     2008.0
2    4.41       16648.0  0439358078  good_reads:book     2003.0
3    3.56       85746.0  0316015849  good_reads:book     2005.0
4    4.23       47906.0  0061120081  good_reads:book     1960.0

                                                year  \
0                                         genre_urls
1  /genres/young-adult|/genres/science-fiction|/g...
2  /genres/fantasy|/genres/young-adult|/genres/fi...
3  /genres/young-adult|/genres/fantasy|/genres/ro...
4  /genres/classics|/genres/fiction|/genres/histo...

                                          genre_urls           dir  \
0                                                dir  rating_count
1                dir01/2767052-the-hunger-games.html     2958974.0
2  dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...     1284478.0
3                          dir01/41865.Twilight.html     2579564.0
4              dir01/2657.To_Kill_a_Mockingbird.html     2078123.0

                                        rating_count             name
0                                               name           author
1            The Hunger Games (The Hunger Games, #1)  Suzanne_Collins
2  Harry Potter and the Order of the Phoenix (Har...      J_K_Rowling
3                            Twilight (Twilight, #1)  Stephenie_Meyer
4                              To Kill a Mockingbird       Harper_Lee

## Exercise 2: Subsetting the data

- Subset the data by creating new dataframe only with `["rating", 'isbn', 'author_url', 'year', 'genre_urls', 'name']`

In [77]:
# making a group based on chosen columns
new_group = df.groupby(['rating', 'isbn', 'author_url', 'year', 'genre_urls', 'name'])

#making a new dataset for the new group
new_group_df = new_group.apply(lambda df: df.loc[:] )

# print the new dataframe
print(new_group_df)

                                                                                                                                                          rating  \
rating isbn       author_url year                                               genre_urls                                         name
2.0    0983650322 2011.0     /genres/young-adult|/genres/science-fiction|/ge... dir38/12393909-revealing-eden.html                 Victoria_Foyt    3736     2.0
2.77   0060988649 2001.0     /genres/fantasy|/genres/fiction|/genres/mystery... dir60/24929.Lost.html                              Gregory_Maguire  5973    2.77
2.97   0395083621 1925.0     /genres/history|/genres/non-fiction|/genres/bio... dir59/54270.Mein_Kampf.html                        Adolf_Hitler     5838    2.97
3.01   0452286530 2004.0     /genres/fiction|/genres/womens-fiction|/genres/... dir52/2152.The_Jane_Austen_Book_Club.html          Karen_Joy_Fowler 5111    3.01
3.03   1416523723 1924.0     /genres/classics|/genres/fiction|/genres/litera... dir51/15613.Billy_Budd_Sailor.html                 Herman_Melville  5062    3.03
...                                                                                                                                                          ...
4.8    1469908530 2012.0     /genres/fantasy                                    dir57/15734769-myrtle-mae-and-the-mirror-in-the... Joe_Egly         5653     4.8
       1475124511 2012.0     /genres/non-fiction|/genres/animals                dir27/16186085-if-i-should-die-before-my-dog---... Joe_Connolly     2630     4.8
4.85   1491732954 2014.0     /genres/fiction                                    dir10/22242097-honor-and-polygamy.html             Omar_Farhad      912     4.85
4.93   1781843457 2013.0     /genres/fantasy|/genres/romance|/genres/suspens... dir38/18080358-blade-heart.html                    Chris_Lange      3710    4.93
rating isbn       year       genre_urls                                         dir                                                author           0     rating

                                                                                                                                                          review_count  \
rating isbn       author_url year                                               genre_urls                                         name
2.0    0983650322 2011.0     /genres/young-adult|/genres/science-fiction|/ge... dir38/12393909-revealing-eden.html                 Victoria_Foyt    3736         368.0
2.77   0060988649 2001.0     /genres/fantasy|/genres/fiction|/genres/mystery... dir60/24929.Lost.html                              Gregory_Maguire  5973         800.0
2.97   0395083621 1925.0     /genres/history|/genres/non-fiction|/genres/bio... dir59/54270.Mein_Kampf.html                        Adolf_Hitler     5838        1399.0
3.01   0452286530 2004.0     /genres/fiction|/genres/womens-fiction|/genres/... dir52/2152.The_Jane_Austen_Book_Club.html          Karen_Joy_Fowler 5111        3072.0
3.03   1416523723 1924.0     /genres/classics|/genres/fiction|/genres/litera... dir51/15613.Billy_Budd_Sailor.html                 Herman_Melville  5062         485.0
...                                                                                                                                                                ...
4.8    1469908530 2012.0     /genres/fantasy                                    dir57/15734769-myrtle-mae-and-the-mirror-in-the... Joe_Egly         5653           8.0
       1475124511 2012.0     /genres/non-fiction|/genres/animals                dir27/16186085-if-i-should-die-before-my-dog---... Joe_Connolly     2630          46.0
4.85   1491732954 2014.0     /genres/fiction                                    dir10/22242097-honor-and-polygamy.html             Omar_Farhad      912           26.0
4.93   1781843457 2013.0     /genres/fantasy|/genres/romance|/genres/suspens... dir38/18080358-blade-heart.html                    Chris_Lange      3710           7.0
rating isbn       year       genre_urls                                         dir                                                author           0     review_count

                                                                                                                                                                isbn  \
rating isbn       author_url year                                               genre_urls                                         name
2.0    0983650322 2011.0     /genres/young-adult|/genres/science-fiction|/ge... dir38/12393909-revealing-eden.html                 Victoria_Foyt    3736  0983650322
2.77   0060988649 2001.0     /genres/fantasy|/genres/fiction|/genres/mystery... dir60/24929.Lost.html                              Gregory_Maguire  5973  0060988649
2.97   0395083621 1925.0     /genres/history|/genres/non-fiction|/genres/bio... dir59/54270.Mein_Kampf.html                        Adolf_Hitler     5838  0395083621
3.01   0452286530 2004.0     /genres/fiction|/genres/womens-fiction|/genres/... dir52/2152.The_Jane_Austen_Book_Club.html          Karen_Joy_Fowler 5111  0452286530
3.03   1416523723 1924.0     /genres/classics|/genres/fiction|/genres/litera... dir51/15613.Billy_Budd_Sailor.html                 Herman_Melville  5062  1416523723
...                                                                                                                                                              ...
4.8    1469908530 2012.0     /genres/fantasy                                    dir57/15734769-myrtle-mae-and-the-mirror-in-the... Joe_Egly         5653  1469908530
       1475124511 2012.0     /genres/non-fiction|/genres/animals                dir27/16186085-if-i-should-die-before-my-dog---... Joe_Connolly     2630  1475124511
4.85   1491732954 2014.0     /genres/fiction                                    dir10/22242097-honor-and-polygamy.html             Omar_Farhad      912   1491732954
4.93   1781843457 2013.0     /genres/fantasy|/genres/romance|/genres/suspens... dir38/18080358-blade-heart.html                    Chris_Lange      3710  1781843457
rating isbn       year       genre_urls                                         dir                                                author           0           isbn

                                                                                                                                                                 booktype  \
rating isbn       author_url year                                               genre_urls                                         name
2.0    0983650322 2011.0     /genres/young-adult|/genres/science-fiction|/ge... dir38/12393909-revealing-eden.html                 Victoria_Foyt    3736  good_reads:book
2.77   0060988649 2001.0     /genres/fantasy|/genres/fiction|/genres/mystery... dir60/24929.Lost.html                              Gregory_Maguire  5973  good_reads:book
2.97   0395083621 1925.0     /genres/history|/genres/non-fiction|/genres/bio... dir59/54270.Mein_Kampf.html                        Adolf_Hitler     5838  good_reads:book
3.01   0452286530 2004.0     /genres/fiction|/genres/womens-fiction|/genres/... dir52/2152.The_Jane_Austen_Book_Club.html          Karen_Joy_Fowler 5111  good_reads:book
3.03   1416523723 1924.0     /genres/classics|/genres/fiction|/genres/litera... dir51/15613.Billy_Budd_Sailor.html                 Herman_Melville  5062  good_reads:book
...                                                                                                                                                                   ...
4.8    1469908530 2012.0     /genres/fantasy                                    dir57/15734769-myrtle-mae-and-the-mirror-in-the... Joe_Egly         5653  good_reads:book
       1475124511 2012.0     /genres/non-fiction|/genres/animals                dir27/16186085-if-i-should-die-before-my-dog---... Joe_Connolly     2630  good_reads:book
4.85   1491732954 2014.0     /genres/fiction                                    dir10/22242097-honor-and-polygamy.html             Omar_Farhad      912   good_reads:book
4.93   1781843457 2013.0     /genres/fantasy|/genres/romance|/genres/suspens... dir38/18080358-blade-heart.html                    Chris_Lange      3710  good_reads:book
rating isbn       year       genre_urls                                         dir                                                author           0            booktype

                                                                                                                                                         author_url  \
rating isbn       author_url year                                               genre_urls                                         name
2.0    0983650322 2011.0     /genres/young-adult|/genres/science-fiction|/ge... dir38/12393909-revealing-eden.html                 Victoria_Foyt    3736     2011.0
2.77   0060988649 2001.0     /genres/fantasy|/genres/fiction|/genres/mystery... dir60/24929.Lost.html                              Gregory_Maguire  5973     2001.0
2.97   0395083621 1925.0     /genres/history|/genres/non-fiction|/genres/bio... dir59/54270.Mein_Kampf.html                        Adolf_Hitler     5838     1925.0
3.01   0452286530 2004.0     /genres/fiction|/genres/womens-fiction|/genres/... dir52/2152.The_Jane_Austen_Book_Club.html          Karen_Joy_Fowler 5111     2004.0
3.03   1416523723 1924.0     /genres/classics|/genres/fiction|/genres/litera... dir51/15613.Billy_Budd_Sailor.html                 Herman_Melville  5062     1924.0
...                                                                                                                                                             ...
4.8    1469908530 2012.0     /genres/fantasy                                    dir57/15734769-myrtle-mae-and-the-mirror-in-the... Joe_Egly         5653     2012.0
       1475124511 2012.0     /genres/non-fiction|/genres/animals                dir27/16186085-if-i-should-die-before-my-dog---... Joe_Connolly     2630     2012.0
4.85   1491732954 2014.0     /genres/fiction                                    dir10/22242097-honor-and-polygamy.html             Omar_Farhad      912      2014.0
4.93   1781843457 2013.0     /genres/fantasy|/genres/romance|/genres/suspens... dir38/18080358-blade-heart.html                    Chris_Lange      3710     2013.0
rating isbn       year       genre_urls                                         dir                                                author           0          year

                                                                                                                                                                                                       year  \
rating isbn       author_url year                                               genre_urls                                         name
2.0    0983650322 2011.0     /genres/young-adult|/genres/science-fiction|/ge... dir38/12393909-revealing-eden.html                 Victoria_Foyt    3736  /genres/young-adult|/genres/science-fiction|/g...
2.77   0060988649 2001.0     /genres/fantasy|/genres/fiction|/genres/mystery... dir60/24929.Lost.html                              Gregory_Maguire  5973  /genres/fantasy|/genres/fiction|/genres/myster...
2.97   0395083621 1925.0     /genres/history|/genres/non-fiction|/genres/bio... dir59/54270.Mein_Kampf.html                        Adolf_Hitler     5838  /genres/history|/genres/non-fiction|/genres/bi...
3.01   0452286530 2004.0     /genres/fiction|/genres/womens-fiction|/genres/... dir52/2152.The_Jane_Austen_Book_Club.html          Karen_Joy_Fowler 5111  /genres/fiction|/genres/womens-fiction|/genres...
3.03   1416523723 1924.0     /genres/classics|/genres/fiction|/genres/litera... dir51/15613.Billy_Budd_Sailor.html                 Herman_Melville  5062  /genres/classics|/genres/fiction|/genres/liter...
...                                                                                                                                                                                                     ...
4.8    1469908530 2012.0     /genres/fantasy                                    dir57/15734769-myrtle-mae-and-the-mirror-in-the... Joe_Egly         5653                                    /genres/fantasy
       1475124511 2012.0     /genres/non-fiction|/genres/animals                dir27/16186085-if-i-should-die-before-my-dog---... Joe_Connolly     2630                /genres/non-fiction|/genres/animals
4.85   1491732954 2014.0     /genres/fiction                                    dir10/22242097-honor-and-polygamy.html             Omar_Farhad      912                                     /genres/fiction
4.93   1781843457 2013.0     /genres/fantasy|/genres/romance|/genres/suspens... dir38/18080358-blade-heart.html                    Chris_Lange      3710  /genres/fantasy|/genres/romance|/genres/suspen...
rating isbn       year       genre_urls                                         dir                                                author           0                                            genre_urls

                                                                                                                                                                                                 genre_urls  \
rating isbn       author_url year                                               genre_urls                                         name
2.0    0983650322 2011.0     /genres/young-adult|/genres/science-fiction|/ge... dir38/12393909-revealing-eden.html                 Victoria_Foyt    3736                 dir38/12393909-revealing-eden.html
2.77   0060988649 2001.0     /genres/fantasy|/genres/fiction|/genres/mystery... dir60/24929.Lost.html                              Gregory_Maguire  5973                              dir60/24929.Lost.html
2.97   0395083621 1925.0     /genres/history|/genres/non-fiction|/genres/bio... dir59/54270.Mein_Kampf.html                        Adolf_Hitler     5838                        dir59/54270.Mein_Kampf.html
3.01   0452286530 2004.0     /genres/fiction|/genres/womens-fiction|/genres/... dir52/2152.The_Jane_Austen_Book_Club.html          Karen_Joy_Fowler 5111          dir52/2152.The_Jane_Austen_Book_Club.html
3.03   1416523723 1924.0     /genres/classics|/genres/fiction|/genres/litera... dir51/15613.Billy_Budd_Sailor.html                 Herman_Melville  5062                 dir51/15613.Billy_Budd_Sailor.html
...                                                                                                                                                                                                     ...
4.8    1469908530 2012.0     /genres/fantasy                                    dir57/15734769-myrtle-mae-and-the-mirror-in-the... Joe_Egly         5653  dir57/15734769-myrtle-mae-and-the-mirror-in-th...
       1475124511 2012.0     /genres/non-fiction|/genres/animals                dir27/16186085-if-i-should-die-before-my-dog---... Joe_Connolly     2630  dir27/16186085-if-i-should-die-before-my-dog--...
4.85   1491732954 2014.0     /genres/fiction                                    dir10/22242097-honor-and-polygamy.html             Omar_Farhad      912              dir10/22242097-honor-and-polygamy.html
4.93   1781843457 2013.0     /genres/fantasy|/genres/romance|/genres/suspens... dir38/18080358-blade-heart.html                    Chris_Lange      3710                    dir38/18080358-blade-heart.html
rating isbn       year       genre_urls                                         dir                                                author           0                                                   dir

                                                                                                                                                                   dir  \
rating isbn       author_url year                                               genre_urls                                         name
2.0    0983650322 2011.0     /genres/young-adult|/genres/science-fiction|/ge... dir38/12393909-revealing-eden.html                 Victoria_Foyt    3736         688.0
2.77   0060988649 2001.0     /genres/fantasy|/genres/fiction|/genres/mystery... dir60/24929.Lost.html                              Gregory_Maguire  5973       11128.0
2.97   0395083621 1925.0     /genres/history|/genres/non-fiction|/genres/bio... dir59/54270.Mein_Kampf.html                        Adolf_Hitler     5838       12417.0
3.01   0452286530 2004.0     /genres/fiction|/genres/womens-fiction|/genres/... dir52/2152.The_Jane_Austen_Book_Club.html          Karen_Joy_Fowler 5111       44813.0
3.03   1416523723 1924.0     /genres/classics|/genres/fiction|/genres/litera... dir51/15613.Billy_Budd_Sailor.html                 Herman_Melville  5062        8978.0
...                                                                                                                                                                ...
4.8    1469908530 2012.0     /genres/fantasy                                    dir57/15734769-myrtle-mae-and-the-mirror-in-the... Joe_Egly         5653          10.0
       1475124511 2012.0     /genres/non-fiction|/genres/animals                dir27/16186085-if-i-should-die-before-my-dog---... Joe_Connolly     2630          81.0
4.85   1491732954 2014.0     /genres/fiction                                    dir10/22242097-honor-and-polygamy.html             Omar_Farhad      912           97.0
4.93   1781843457 2013.0     /genres/fantasy|/genres/romance|/genres/suspens... dir38/18080358-blade-heart.html                    Chris_Lange      3710          15.0
rating isbn       year       genre_urls                                         dir                                                author           0     rating_count

                                                                                                                                                                                               rating_count  \
rating isbn       author_url year                                               genre_urls                                         name
2.0    0983650322 2011.0     /genres/young-adult|/genres/science-fiction|/ge... dir38/12393909-revealing-eden.html                 Victoria_Foyt    3736               Revealing Eden (Save the Pearls, #1)
2.77   0060988649 2001.0     /genres/fantasy|/genres/fiction|/genres/mystery... dir60/24929.Lost.html                              Gregory_Maguire  5973                                               Lost
2.97   0395083621 1925.0     /genres/history|/genres/non-fiction|/genres/bio... dir59/54270.Mein_Kampf.html                        Adolf_Hitler     5838                                         Mein Kampf
3.01   0452286530 2004.0     /genres/fiction|/genres/womens-fiction|/genres/... dir52/2152.The_Jane_Austen_Book_Club.html          Karen_Joy_Fowler 5111                          The Jane Austen Book Club
3.03   1416523723 1924.0     /genres/classics|/genres/fiction|/genres/litera... dir51/15613.Billy_Budd_Sailor.html                 Herman_Melville  5062                                 Billy Budd, Sailor
...                                                                                                                                                                                                     ...
4.8    1469908530 2012.0     /genres/fantasy                                    dir57/15734769-myrtle-mae-and-the-mirror-in-the... Joe_Egly         5653  Myrtle Mae and the Mirror in the Attic (The Ma...
       1475124511 2012.0     /genres/non-fiction|/genres/animals                dir27/16186085-if-i-should-die-before-my-dog---... Joe_Connolly     2630                   If I Should Die Before My Dog --

C:\Users\MSI\AppData\Local\Temp\ipykernel_11000\2960669036.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  new_group_df = new_group.apply(lambda df: df.loc[:] )

## Exercise 3: Manage Missing Data
We’ve got a number of ways in general of dealing with missing data. These involve

1. Dropping off cases (or rows) in the data with any missing variables
2. Excluding variables in the data with any missing data 
3. Selectively choosing indicators with only a limited amount of missing data
4. Replacing missing variables with averages, or other representative values
5. Creating a separate model to predict missing data

- Count the missing values in each column
- Manage the missing values (delete or replace values or leave them as they are) and briefly explain your choice for each column

In [78]:
# to count the missing values of each column
Missing_value_Count = df.isnull().sum()
print(Missing_value_Count)

rating            0
review_count      0
isbn            471
booktype          0
author_url        0
year             59
genre_urls        0
dir               0
rating_count      0
name              0
dtype: int64

In [79]:
# isbn is a chainof numbers, genre_urls are urls. their number count is high, replace NaN with "Unknown"

df.isbn.fillna("Unknown")
df.genre_urls.fillna("Unknown")

0                                                     dir
1                     dir01/2767052-the-hunger-games.html
2       dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...
3                               dir01/41865.Twilight.html
4                   dir01/2657.To_Kill_a_Mockingbird.html
                              ...
5989                  dir60/78508.The_River_of_Doubt.html
5990                               dir60/259068.Shug.html
5991                           dir60/13503247-flawed.html
5992                                   dir60/2750008.html
5993    dir60/66677.Legacy_of_the_Drow_Collector_s_Edi...
Name: genre_urls, Length: 5994, dtype: object

In [80]:
# other columns missing part is not significant. we can discard them in

df = df[df.rating.notnull()]
df = df[df.review_count.notnull()]
df = df[df.booktype.notnull()]
df = df[df.author_url.notnull()]
df = df[df.year.notnull()]
df = df[df.rating_count.notnull()]
df = df[df.name.notnull()]
#
df.dtypes

rating          object
review_count    object
isbn            object
booktype        object
author_url      object
year            object
genre_urls      object
dir             object
rating_count    object
name            object
dtype: object

## Exercise 4: Shape the data
- Parse the `author_url` to create new column named `author`
- Sort the data by putting higher rates go first. If there are overlapping rates, try to put earlier years go first.
- **(Stretch Goal)** Examine how many books were published at each year and find lowest, highest rate of each year.

In [81]:
# Getting the author_url
test_string = df.author_url[:]
test_string

0         year
1       2008.0
2       2003.0
3       2005.0
4       1960.0
         ...
5989    2005.0
5990    2006.0
5991    2012.0
5992    2006.0
5993    2001.0
Name: author_url, Length: 5935, dtype: object

In [82]:
# a function to get URL and give us Authors name

def get_author(url):

    author = url.split('/')[-1].split('.')[1:][0]
     
    return author

In [83]:
# Using '.map' to apply the get_author function to the 'author_url' column. Create a new column 'author' to contain the names.
df['author'] = df.author_url.map(get_author)

# to test if the code is working
df.author[0:5]

IndexError: list index out of range

In [71]:
# sorting the data in a way that higher rating go first, and if the rating were equal, the newer book is shown first.
df.groupby(['rating', 'year']).rating.agg([len, max, min])

C:\Users\MSI\AppData\Local\Temp\ipykernel_11000\4120032659.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby(['rating', 'year']).rating.agg([len, max, min])
C:\Users\MSI\AppData\Local\Temp\ipykernel_11000\4120032659.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby(['rating', 'year']).rating.agg([len, max, min])

               len   max   min
rating year
2.00   2011.0    1  2.00  2.00
2.77   2001.0    1  2.77  2.77
2.90   2013.0    1  2.90  2.90
2.97   1925.0    1  2.97  2.97
3.01   2004.0    1  3.01  3.01
...            ...   ...   ...
4.93   2013.0    1  4.93  4.93
4.94   2014.0    1  4.94  4.94
5.00   2011.0    1  5.00  5.00
       2012.0    4  5.00  5.00
       2014.0    2  5.00  5.00

[3514 rows x 3 columns]

## Exercise 5: Saving the results
- Save the cleaned dataframe as 'hw-03-cleaned.csv' in data folder

In [72]:

# do delete Author_url column
del df['author_url']

# to save the new dataframe
df.to_csv("C:\\Users\\MSI\\Documents\\Data_one\\goodreads.csv", index=False, header=True)

## Exercise 6: Investigate the relationship between the number of reviews and the average rating for books in the dataset cleaned-goodreads.csv procided.

- Calculate the correlation coefficient. Give me a short definition of this coefficient
- Create a scatter plot showing the relationship between these two features.
- Based on the plot and the correlation, provide a brief interpretation of the relationship.

### Python Tools: Use pandas and numpy for correlation, and matplotlib or seaborn for the scatter plot.

In [73]:

# calculating the Pearson correlation between number of reviews and the average rating
corr = df["review_count"].corr(df['rating'])
# display the correlation
print(corr)

-0.037896372578752904

## Exercise 7: Calculate the following descriptive statistics for the numerical features (e.g., number of reviews, average rating, etc.):
- Mean
- Median
- Standard Deviation
- Range
- Create a histogram or box plot for at least one of the numerical features, highlighting any skewness or outliers.
    
### Python Tools: Use pandas for data manipulation and matplotlib or seaborn for visualization.

In [ ]:
# your code here
# use many cells if you like to structure your code well